### ISSUE TITLE
Tox support do python 3.5+ versions

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/splitty#13]
Tox only run in one version of python. The version of container used in [circle-CI file](https://github.com/dunossauro/splitty/blob/master/circle.yml#L3). We can add support in last three versions of python. Actually

- 3.5
- 3.6
- 3.7

**Comment by browniebroke** [comment]
FYI #17 for #14

**Comment by dunossauro** [comment]
Issue solved in #19 

:heart:
