### ISSUE TITLE
Move CI from Circle-CI to Travis-ci

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/splitty#14]

**Comment by browniebroke** [comment]
I can work on this

**Comment by browniebroke** [comment]
Can you please enable it here: https://travis-ci.org/dunossauro/splitty/

I'll write the config

**Comment by dunossauro** [comment]
@browniebroke. Thanks a lot :heart: 

I enable travis-ci on https://travis-ci.org/dunossauro/splitty/

<3

**Comment by browniebroke** [comment]
Should I remove the Circle CI config?

**Comment by dunossauro** [comment]
@browniebroke Would you like me to create an issue for this?

**Comment by browniebroke** [comment]
No need I think. Will send another PR

**Comment by dunossauro** [comment]
@browniebroke, oh... Nice


Thanks <3
